version: "3.9"

services:
  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo_hubees
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=hubees
      - MONGODB_PASSWORD=123456
      - MONGODB_DATABASE=mongo_hubees
    volumes:
      - mongodb:/data/db/mongo
      
  redis:
    image: bitnami/redis:latest
    container_name: redis_hubees
    volumes:
      - redisdb:/data/db/redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_hubees
    volumes:
      - rabbitmqdb:/data/db/rabbitmq
    ports:
      - "5672:5672"

  postgres:
    image: postgres
    container_name: pg_hubees
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=new
      - POSTGRES_DB=hubees
      - PGPORT=5432
    volumes:
      - postgresdb:/data/db/postgres

  app:
    build: .
    container_name: api_hubees
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - postgres
      - redis
      - mongo
      - rabbitmq
    depends_on:
      - postgres
      - redis
      - mongo
      - rabbitmq

volumes:
  mongodb:
    driver: local

  redisdb:
    driver: local

  rabbitmqdb:
    driver: local

  postgresdb:
    driver: local
